version: '3'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: med_reconciliation_appuser
      POSTGRES_PASSWORD: medreconuser
      POSTGRES_DB: med_reconciliation_app
    ports:
      - "5432:5432"
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/med_reconciliation_app
      SPRING_DATASOURCE_USERNAME: med_reconciliation_appuser
      SPRING_DATASOURCE_PASSWORD: medreconuser
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    depends_on:
      - db