name: Build and Test

on:
  push:
    branches: [ "features/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Docker
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2'

      - name: Log in to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Start Docker Compose
        run: docker compose up -d

      - name: Build with Maven
        run: mvn clean verify -DskipTests=true

      - name: Test Dockerfile
        run: docker build -t med-reconciliation-app

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
         name: build-artifacts
         path: |
           target/classes
           target/site
